# 将静态内容部署到 GitHub Pages 的简单工作流
将静态内容部署到 Pages

事件:
  # 仅在推送到默认分支时运行
 推送:
    分支: ["main"]

  # 允许您从“操作”选项卡手动运行此工作流
 工作流调度:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
权限:
 内容: 读取
 页面: 写入
 id-token: 写入

# 仅允许一次并发部署，跳过在当前运行与最新排队之间发生的排队运行。
不过，请勿取消正在进行的运行，因为我们希望这些生产部署能够顺利完成。
并发:
 组: "pages"
 取消中: false

作业:
  # 由于我们只是进行部署，因此使用单个部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
